crowdbotics/modules

demo/.circleci/config.yml, dist/cookie/{{cookiecutter.project_slug}}/.circleci/config.yml, dist/raw/ProjectName/.circleci/config.yml, scaffold/template/custom/.circleci/config.yml
Changes CircleCI docker image tag version to `14.16.0`
=> Upgrade CircleCI node image version

demo/README.md, demo/yarn.lock, dist/cookie/{{cookiecutter.project_slug}}/README.md, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/README.md, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/README.md
- Add yarn command
- Add fastlane commands
=> Docs - Update User README

demo/README.md, demo/config-overrids.js, demo/package.json, demo/public/index.html, demo/yarn.lock, dist/cookie/{{cookiecutter.project_slug}}/README.md, dist/cookie/{{cookiecutter.project_slug}}/config-overrids.js, dist/cookie/{{cookiecutter.project_slug}}/package.json, dist/cookie/{{cookiecutter.project_slug}}/public/index.html, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/README.md, dist/raw/ProjectName/config-overrids.js, dist/raw/ProjectName/package.json, dist/raw/ProjectName/public/index.html, dist/raw/ProjectName/yarn.lock, scaffold/install.js, scaffold/template/custom/README.md, scaffold/template/custom/config-overrides.js, scaffold/template/custom/package.json, scaffold/template/custom/public/index.html
Based on https://github.com/crowdbotics/react-native-scaffold/pull/250
=> Feature: Add react-native-web support

demo/.crowdbotics.json, demo/yarn.lock, dist/cookie/{{cookiecutter.project_slug}}/.crowdbotics.json, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/.crowdbotics.json, dist/raw/ProjectName/yarn.lock, scaffold/install.js, scaffold/template/custom/.crowdbotics.json
This PR adds `.crowdbotics.json` in the template with the following content:
```json
{
"scaffold": {
"type": "react-native",
"version": "1.0.0"
}
}
```
This will help us differentiate apps on the old scaffold, or on newer versions of the new system.
=> Add .crowdbotics.json dotfile

demo/metro.config.js, demo/yarn.lock, dist/cookie/{{cookiecutter.project_slug}}/metro.config.js, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/metro.config.js, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/metro.config.js
@screens wasn't setup on metro yet, this PR adds to the config
=> Proxy @screens dependencies to root

demo/package.json, demo/yarn.lock, dist/cookie/{{cookiecutter.project_slug}}/package.json, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/package.json, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/dependencies.json
Removed datepicker from scaffold and ran `npm run bootstrap`
=> Remove datepicker from scaffold

dist/cookie/{{cookiecutter.project_slug}}/App.js, dist/cookie/{{cookiecutter.project_slug}}/modules/index.js, dist/cookie/{{cookiecutter.project_slug}}/modules/utils.js, scaffold/template/custom/App.js, scaffold/template/custom/modules/index.js, scaffold/template/custom/modules/utils.js
- add function to find a screen for navigation 
- not show navigation header (as old scaffold requirement). In the future, we should expose a param to configure navigation header option
=> Improvements

dist/cookie/{{cookiecutter.project_slug}}/App.js, dist/cookie/{{cookiecutter.project_slug}}/modules/index.js, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/App.js, dist/raw/ProjectName/modules/index.js, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/App.js, scaffold/template/custom/modules/index.js
- cookiecutter issue with {{ }}
- revert changes: moving screens to modules
=> Hotfix 0618

scripts/demo.js
specified for cookiecutter to run command using python
=> specified cookiecutter to run with python

dist/cookie/{{cookiecutter.project_slug}}/README.md, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/README.md, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/README.md
adding modules section to README
=> add modules section to README

dist/cookie/{{cookiecutter.project_slug}}/.github/dependabot.yml
Ticket: [PLAT-5491](https://crowdbotics.atlassian.net/browse/PLAT-5491)
=> add dependabot config for rn scaffold

scaffold/template/custom/App.js
PLAT-XXXX
_Related PRs:_
Regression bug fix.
Last regression:
https://github.com/crowdbotics/modules/commit/4f0ff2f80acaef168b1900b10c4345270da5cf25
Check commit linked above
=> Add spaces to jsx object prop

dist/cookie/{{cookiecutter.project_slug}}/App.js, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/App.js, dist/raw/ProjectName/yarn.lock
PLAT-XXXX
_Related PRs:_
Missed `yarn run bootstrap` on #73
N/A
=> yarn run bootstrap

modules/react-native-login/README.md, modules/react-native-login/auth/api.js, modules/react-native-login/index.js, modules/react-native-login/options.js, modules/react-native-login/screens/constants.js, modules/react-native-login/screens/loginsignup.js, modules/react-native-login/screens/reset.js
N/A
- [ X] New feature
This adds support for the Login Module to use Module Options. It includes support for setting the following via module options: 
- configure the authentication URL the module points to (set via global options)
- configure which image urls to use as background and logo, 
- choose where to redirect a user after a successful login-
- change email validation logic 
- set custom text for toggle and sign in/sign up buttons
I did not include style (aside from the image and logo urls) as I thought it would make the resulting options.js file too big and complex for users, though I could go back and add them if that's deemed best.
Install the module and see if you can get it working with the module option configurations included in the Readme.
=> Update Login Module Options

dist/cookie/{{cookiecutter.project_slug}}/.circleci/config.yml, dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/res/values/strings.xml, dist/cookie/{{cookiecutter.project_slug}}/ios/fastlane/Appfile, dist/cookie/{{cookiecutter.project_slug}}/ios/fastlane/Fastfile, dist/cookie/{{cookiecutter.project_slug}}/ios/{{cookiecutter.project_slug}}/Info.plist, dist/raw/ProjectName/.circleci/config.yml, dist/raw/ProjectName/ios/fastlane/Appfile, dist/raw/ProjectName/ios/fastlane/Fastfile, scaffold/template/custom/.circleci/config.yml, scaffold/template/custom/ios/fastlane/Appfile, scaffold/template/custom/ios/fastlane/Fastfile, scripts/cookie.js
PLAT-5707
- App Store builds on the new scaffold (modules)
- create app
- deploy ios build
=> PLAT-5707: App Store build on new scaffold (modules)

modules/react-native-login/constants.js, modules/react-native-login/options.js, modules/react-native-login/screens/loginsignup.js, modules/react-native-login/screens/reset.js, modules/react-native-social-login/screens/constants.js
Per several discussions on slack in #module-options.
Removes variable references from the Login modules `options.js` file, which is necessary to make this module compatible with our first release of Module Options.
I've tested this module by installing it in the demo app alongside app-menu. I then configured the global `options/options.js` url to point to a demo app for authentication purposes (note that the authentication url for login is set via global options, not module options). Eg:
```
//options.js
export const globalOptions = {
name: "demo",
url: "https://ben-mo-option-be-te-30759.botics.co/",
api: "https://demo.botics.co/api/v1"
}
```
The URL: https://ben-mo-option-be-te-30759.botics.co/ is a demo app you should be able to use to test against as well. 
Note that (afaik) we will …
=> Remove variable references from Login Module Options.js

modules/react-native-app-menu/meta.json
PLAT-5696
_Related PRs:_ #128
Adds types schema to the App Menu module.
`yarn run parse` should run successfully.
=> Options Types - Add types to react-native-app-menu

modules/django-articles/articles/models.py
PLAT-5714
_Related PRs:_ https://github.com/crowdbotics/crowdbotics-slack-app/pull/3290 https://github.com/crowdbotics/django-scaffold/pull/280
Adding `get_options` to module django-articles
1. Create a new app and install module django-articles
2. The models should now have `get_options` method imported from `modules.utils`
=> PLAT-5714 Python Parser Upgrade (Modules)

dist/cookie/{{cookiecutter.project_slug}}/.circleci/generate_mobile_config.sh, dist/raw/ProjectName/.circleci/generate_mobile_config.sh, scaffold/template/custom/.circleci/generate_mobile_config.sh
PLAT-6776
_Related PRs:_ https://github.com/crowdbotics/react-native-scaffold/pull/315
_Update CircleCI docker image_
=> PLAT-6776 Update CircleCI docker image

modules/screen-login/index.js
Removes the extra curly braces from the import statement
N/A
=> screen-login - Remove extra curly braces from import

docs/authoring.md, modules/screen-login/index.js
This PR changes the export for the login screen module to be a default export.
=> Login Screen - Change named export to default export

docs/commands.md, docs/index.md
This PR updates the docs index page links base path to work on Github Pages
=> Docs - Fix docs index page links

.eslintignore, .eslintrc.json, .prettierrc, package.json, scripts/add.js, scripts/config.js, scripts/info.js, scripts/parse.js, scripts/raw.js, scripts/remove.js, scripts/template.js
Updates to `scripts/parse.js` to validate screen only modules.
Runs those checks:
https://github.com/crowdbotics/modules/pull/261#pullrequestreview-977136418
=> Feature: validate screen modules w/ scripts/parse

modules/screen-social-profile/index.js
Adds missing import and runs `yarn run parse`
=> Hotfix: add missing import to screen-social-profile

dist/cookie/{{cookiecutter.project_slug}}/package.json, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/package.json, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/dependencies.json
PLAT-8004
Adding the radio buttons package so we can use it on Studio
yarn run demo
cd demo
bundle install
cd android
bundle exec fastlane deploy_appetize
=> PLAT-8004: Add react-native-radio-buttons-group to scaffold

modules/screen-terms-and-conditions/index.js
=> screen-terms-and-conditions Added

modules/screen-suggest-a-feature/index.js
=> screen-suggest-a-feature Added

modules/screen-privacy-policy/index.js
=> screen-privacy-policy Added

modules/screen-add-card-details/index.js
=> screen-add-card-details Added

modules/screen-bond-nft/index.js
=> screen-bond-nft Added

modules/screen-register/index.js
=> screen-register

modules/screen-stripe-registration/index.js
=> screen-stripe-registration

.github/pull_request_template.md
Added two review checklists, one for when making changes to modules and one for when making changes to the scaffold. Those should help PR authors validate their work before asking for a review.
- Is there anything else that we should add to the checklists?
- Is there anything that we should remove from them?
=> Review checklist for module and scaffold updates

modules/react-native-app-menu/index.js, modules/react-native-app-menu/options.js
This PR adds `ScrollView` and `SafeAreaView` around the App Menu module. Improved the styling of global options.
Run App Menu with enough modules added so that it can scroll. Verify that it works.
=> Modules - Add scrolling capabilities to App Menu

dist/cookie/{{cookiecutter.project_slug}}/package.json, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/package.json, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/package.json
PLAT-9201
_Related PRs:_
In order to run the included demo app, run `yarn run bootstrap` and then `cd demo` and run both `npx react-native run-android` and `npx react-native start` in parallel.
Please go through the following checks:
Django modules specific checks:
If your module is a "supermodule" and therefore contains both React Native and Django code, then please go through all of the checks above.
=> PLAT-9201 - React native dependency failling

modules/screen-subscription-trial/index.js
=> screen-subscription-trial added

modules/screen-link-bank-account/index.js
=> screen-link-bank-account added

.github/workflows/release.yml
PLAT-5748
_Add initial GH config to enable the workflow_
=> PLAT-5748 Add initial GH config to enable the workflow

.github/workflows/release.yml, README.md
PLAT-5748
_Add GH workflow to release modules in `staging` and `production` environment on merge event to `develop` and `master` branch respectively._
- Successful GH workflow execution for staging environment-https://github.com/crowdbotics/modules/actions/runs/4116899196
=> PLAT-5748 Add GH release workflow

dist/cookie/{{cookiecutter.project_slug}}/Dockerfile, dist/raw/ProjectName/Dockerfile, scaffold/template/custom/Dockerfile
PLAT-10339
_Related PRs:_
In order to run the included demo app, run `yarn run bootstrap` and then `cd demo` and run both `npx react-native run-android` and `npx react-native start` in parallel.
Please go through the following checks:
Django modules specific checks:
If your module is a "supermodule" and therefore contains both React Native and Django code, then please go through all of the checks above.
Updated the Dockerfile from `dist/cookie/{{cookiecutter.project_slug}}/Dockerfile`
Creating new Apps should contain the new updated Dockerfile
=> PLAT-10339 Installing django-modules breaks the app deployment

.github/workflows/release.yml, README.md
Merge `develop` branch onto `master` branch for release.
=> Merge develop onto master

.github/workflows/release.yml
_Related tickets:_ PLAT-10263
Added tags pattern to the release github action and added `heroku config:set` command for updating the environment variable.
Tagging a release should set `REACT_NATIVE_SCAFFOLD_REPO_BRANCH` env var to the git tag name and run the management command.
=> release to production from git tags

dist/cookie/{{cookiecutter.project_slug}}/App.js, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, dist/raw/ProjectName/App.js, dist/raw/ProjectName/yarn.lock, scaffold/template/custom/App.js
PLAT-11377 
_Related PRs:_https://github.com/crowdbotics/vue-dash-5104/pull/3860
Simple PR for changing headerShown to false
In order to run the included demo app, run `yarn run bootstrap` and then `cd demo` and run both `npx react-native run-android` and `npx react-native start` in parallel.
Please go through the following checks:
Django modules specific checks:
If your module is a "supermodule" and therefore contains both React Native and Django code, then please go through all of the checks above.
=> PLAT-11377 Modules: Changed header from true to false

config.js, docs/commands.md
Since we squash and merge PRs one can only know the SHA of the commit after a merge to master happens. This is a followup to #875.
Running `yarn run manifest` should not produce changes.
=> Upgrade - add version 2.0.0 commit SHA

README.md, docs/index.md
- Fixes the main README.md documentation link (was pointing to a directory, now points to the docs website).
- Fixes the links in the docs website.
Links should be working after this gets deployed.
=> Documentation: Fix docs links

docs/index.md
Add links to changelog and repository.
You should be able to go to the changelogs from the webstie.
=> docs: add link to changelog and repo

Pipfile.lock, config.js, dist/cookie/{{cookiecutter.project_slug}}/.crowdbotics.json, dist/cookie/{{cookiecutter.project_slug}}/App.js, dist/cookie/{{cookiecutter.project_slug}}/babel.config.js, dist/cookie/{{cookiecutter.project_slug}}/package.json, dist/cookie/{{cookiecutter.project_slug}}/webpack.config.js, dist/cookie/{{cookiecutter.project_slug}}/yarn.lock, manifest/230-to-240.json, scaffold/CHANGELOG.md, scaffold/package.json, scaffold/template/custom/.crowdbotics.json, scaffold/template/custom/App.js, scaffold/template/custom/babel.config.js, scaffold/template/custom/dependencies.json, scaffold/template/custom/webpack.config.js
PLAT-11650
React Native Paper in the scaffold
=> PLAT-11650-React Native Paper as part of the scaffold

.github/pull_request_template.md, docs/authoring-modules.md, docs/commands.md, docs/modules-checklist.md, docs/scaffold-checklist.md
Docs for how to test scaffold updates on Studio. Fixed links in github pages website.
=> docs: how to test scaffold updates on Studio

modules/camera/modules/camera/utils.js, modules/faq/modules/faq/FAQItem.js, modules/faq/modules/faq/index.js, modules/firebase-push-notifications/modules/firebase-push-notifications/index.js, modules/react-native-appointment/screens/appointmentList.js, modules/react-native-appointment/screens/calendar.js, modules/react-native-appointment/screens/createAppointment.js, modules/react-native-chat/index.js, modules/react-native-live-camera-filters/index.js, modules/react-native-photo-editing/Screens/crop/index.js, modules/react-native-photo-editing/Screens/edits/index.js, modules/react-native-photo-editing/Screens/filters/index.js, modules/react-native-photo-editing/Screens/imagePicker/index.js, modules/react-native-photo-editing/Screens/shadows/index.js, modules/react-native-privacy-policy-webview/index.js, modules/react-native-social-login/auth/apple.js, modules/react-native-social-login/index.js, modules/react-native-social-login/screens/loginsignup.js, modules/react-native-social-login/screens/reset.js, modules/react-native-terms-and-conditions-webview/index.js, modules/react-native-typeform-webhook/options.js, modules/react-native-zoom-free-calling/index.js
=> PLAT-11697-Fix modules issues and refactor their source code

modules/react-native-fingerprint-authentication/README.md, modules/react-native-fingerprint-authentication/index.js, modules/react-native-fingerprint-authentication/package.json
upgrade package and update readme for new scaffold 0.71.7 fix
=> Fix: React Native fingerprint authentication (0.71.7)

modules/django-files/django_files/files/README.md, modules/django-files/django_files/files/models.py, modules/django-files/django_files/files/serializers.py, modules/django-files/django_files/files/tests.py, modules/django-files/django_files/files/urls.py, modules/django-files/django_files/files/viewsets.py
1. Module setup commands and added api endpoints table
=> Files Module (Backend): Optimization for enterprise

modules/react-native-login/README.md
added module  scope features, api call methods and license  in README.md file.
=> Updated-Readme: Login Module

modules/react-native-terms-and-conditions-webview/README.md
added module specifications, scope features and dependencies installation in README.md file.
=>  Updated-Readme: Terms And Conditions Webview

.github/workflows/release.yml
PLAT-11982
_Adds JIRA label to tickets based on release environment_
=> PLAT-11982 add JIRA labels

package.json, yarn.lock
PLAT-12216
_Related PRs:_
Upgrade shell-quote to 1.7.3 via resolution as per  https://github.com/crowdbotics/modules/security/dependabot/27
=> Added resolution for vulnerable shell quote package

.github/workflows/release.yml
PLAT-11982
- _Pull repo tags_
- _Show tickets which will be updated_
=> PLAT-11982 pull git tags

modules/react-native-privacy-policy-webview/README.md
add module specifications and dependencies setup installation in README.md file.
=> Update-Readme: Privacy Policy Webview

.github/workflows/app-release.yml
[PLAT-XXXX](https://crowdbotics.atlassian.net/browse/PLAT-11893)
_Related PRs:_
- Add Github action release configuration
=> PLAT-11893-Add release configuration

modules/react-native-qr-code/README.md, modules/react-native-qr-code/components/QrGenerator/index.js, modules/react-native-qr-code/index.js, modules/react-native-qr-code/store/api.js, modules/react-native-qr-code/store/index.js
Update readme
Implemented store
=> RN-Qr-code: Update readme & Store implementation

modules/django-social-auth/django_social_auth/social_auth/README.md, modules/django-social-auth/django_social_auth/social_auth/views.py
_Bug fixes django social auth module
=> Bug Fixes: django social auth module

modules/django-docusign/django_docusign/docusign/README.md, modules/django-docusign/django_docusign/docusign/viewsets.py, modules/django-docusign/django_docusign/setup.py
Rename env variable and update setup.py
=> Django Docusign: Bug Fixes

modules/django-video-uploader/django_video_uploader/setup.py
=> Django Video Uploader (Vimeo): Bug Fixes

.github/workflows/release.yml
[PLAT-12152](https://crowdbotics.atlassian.net/browse/PLAT-12152)
_Related PRs:_ [CB app PR 4936](https://github.com/crowdbotics/crowdbotics-slack-app/pull/4936)
Added new parameters in `update_crowdbotics_modules` command.
Described in [PR 4936](https://github.com/crowdbotics/crowdbotics-slack-app/pull/4936)
[PLAT-12152]: https://crowdbotics.atlassian.net/browse/PLAT-12152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-12152: adding parameters to update modules command

modules/azure-infra/README.md, modules/azure-infra/meta.json
[PLAT-12373](https://crowdbotics.atlassian.net/browse/PLAT-12373)
_Related PRs:_  #972 
_Add deployment instructions to `README.md` for azure module_
[PLAT-12373]: https://crowdbotics.atlassian.net/browse/PLAT-12373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-12373 Add deployment instruction for azure module

.github/workflows/app-release.yml, .github/workflows/release.yml
Added `--size=standard-2x` to the heroku command.
Release workflow should not fail with OOM errors.
=> Release Workflow - Set dyno size

index.js
Ensure dir exists before writing output file when parsing.
Release should not fail.
=> scripts/parse: mkdir before writing to file

modules/social-feed/backend/modules/social-feed/views.py
Bug fix in create post viewsets
=> Social Feed Module (Bug Fixes)

modules/firebase-push-notifications/modules/firebase-push-notifications/api.js
Update device registration endpoint in `api.js` file
=> Update device registration endpoint (Bug Fixes)

modules/react-native-chat/utils.js
Change the directory path of files from temporary to document directory.
=> Update destination path for files (Bug Fixes)

.github/workflows/app-release.yml
PLAT-12749
_Related PRs:_ https://github.com/crowdbotics/github-actions/pull/2
_switch to reusable release workflow_
=> PLAT-12749 switch to reusable release workflow

.github/dependabot.yml
PLAT-12462
_Related PRs:_
_Use `Dependabo` to update repo actions_
=> PLAT-12462 Dependabot: enable action update

CHANGELOG.md, package.json, scripts/add.js
PLAT-13011
Run `pipenv install -e ./modules/<module-directory`
All of the following commands should work without errors:
```
npx . demo
npx . add camera
npx . add react-native-app-menu
npx . add django-files
```
=> PLAT-13011 - Feature: install python modules

index.js, scripts/info.js, scripts/login.js, scripts/utils/auth.js, scripts/utils/configFile.js, scripts/utils/constants.js
Plat-13077
Introducing initial WIP for logging in using the existing auth api into the cli. Upon successful login, using a new configFile class, the command will write the current token to `~/.crowdbotics/auth.json`. This path uses a cross-environment home path (for windows, linux, and macosx).
Finally, a user can run a simple protected api command to prove the token is working.
1. `cbx login` - Various states of failure and success
2. `cbx info` - Display the current user. Handles error state if no token or token is invalid
=> Plat-13077 authentication

index.js, scripts/info.js, scripts/utils/apiClient.js, scripts/utils/auth.js, scripts/utils/constants.js
Plat-13077
_Related PRs:_
- Adding config command, which allows the user to manage their config settings via the CLI.
- Abstracting api calls to an api client
- Allowing configurable host path for api
=> Plat 13077 api client v2

package.json, scripts/utils/apiClient.js, yarn.lock
Plat-13077
_Related PRs:_
Migrating to node fetch to support node v16 and below
=> PLAT-13077: Migrating to use node fetch

index.js, package.json, scripts/info.js, scripts/login.js, scripts/utils/apiClient.js, scripts/utils/auth.js, scripts/utils/configFile.js, scripts/utils/constants.js, yarn.lock
PLAT-13077
- Merging commits already reviewed from long running feature branch into main
=> Plat-13077 feature branch

CHANGELOG.md, package.json
PLAT-13077
- Bumping version
- Updating changelog
=> PLAT-13077: Adding changelog

package.json, scripts/utils/organization.js, yarn.lock
PLAT-13169
_Related PRs:_
Adding ora, which is a command loading spinner library
Adding an organization util to get the current users org.
=> PLAT-13169: Adding a few components to be used in different feature branches

index.js, package.json, scripts/modules.js, yarn.lock
PLAT-13085
Adding modules list command, with some basic search capabilities
More search flags are pending
Search usage:
Basic Pagination:
=> Plat 13085 list modules

index.js, scripts/modules.js
Plat-13085
_Related PRs:_
- Adding help text
=> Adding basic help text

.github/workflows/lint.yml, .github/workflows/parse.yml, .github/workflows/release.yml
=> PLAT-13283 update workflow

index.js, scripts/feedback.js
=> PLAT-13091 User can send product feedback

index.js, scripts/modules.js, scripts/utils/apiClient.js, scripts/utils/constants.js, scripts/utils/url.js
Plat-13083
Adding the ability to get module details by id
Cleaning up url handling so that we can build web routes from the HOST config value too
- Get modules by id, validate details
- Click supplied link to see if it works
=> Plat 13083 get module

scripts/utils/apiClient.js
PLAT-13083
_Related PRs:_
Fixing broken url building in api client due to missing trailing slash
=> PLAT-13083: Fixing url building to always have trailing slash

scripts/modules.js
PLAT-13167
`cli` change to match the back-end change where we filter out modules that do not have code in them (and are not meant to be installed).
Check that modules list only returns modules that contain code.
Before:
```sh
aline@GU603HM:~/crowdbotics/modules$ npx . modules list
┌──────────┬──────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│ id       │ Title                                            │ Description                                                                    │
├──────────┼──────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ 239      │ 14-Day …
```
=> PLAT-13167: Display code-only modules in list

index.js, package.json, scripts/feedback.js, scripts/logout.js, scripts/modules.js, scripts/publish.js, scripts/utils/apiClient.js, scripts/utils/auth.js, scripts/utils/constants.js, scripts/utils/organization.js, scripts/utils/url.js, yarn.lock
PLAT-XXXX
_Related PRs:_
Merge CLI feature branch into develop
=> Modules feature branch - Merge CLI tickets into develop

CHANGELOG.md
PLAT-XXXX
_Related PRs:_
Changelog updates.
N/A
=> Chore: include CHANGELOG for release

.github/workflows/lint.yml, .github/workflows/parse.yml, .github/workflows/release.yml, CHANGELOG.md, index.js, package.json, scripts/feedback.js, scripts/logout.js, scripts/modules.js, scripts/publish.js, scripts/utils/apiClient.js, scripts/utils/auth.js, scripts/utils/constants.js, scripts/utils/organization.js, scripts/utils/url.js, yarn.lock
=> Sync branches

index.js
Introduced `publish` command on the output of the `help` command and a brief description of it.
Run ```npx crowdbotics/modules#docs/add-publish-command``` and see the result.
=> Docs - document publish command on the help command

scripts/modules.js
PLAT-13362
Updating deep link to point to new top level catalog
=> PLAT-13362: Updating url of module catalog

.github/workflows/release-to-qa.yml
[PLAT-13351](https://crowdbotics.atlassian.net/browse/PLAT-13351)
_Related PRs:_
Add workflow release-to-qa.yml
[PLAT-13351]: https://crowdbotics.atlassian.net/browse/PLAT-13351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-13351 Add action Release to QA

index.js, scripts/modules.js
Merge QA to master for production release.
=> Merge to master for release

.github/workflows/create-github-release.yml
=> CBDEVOPS-373 clone and use reusable workflow

index.js, scripts/modules.js
PLAT-13444
_Related PRs:_
Adding the ability to manage archiving of modules
Archive module
Unarchive module
List module by status
=> PLAT-13444 archive module

scripts/info.js, scripts/modules.js
PLAT-13541
_Related PRs:_
- Updating modules cli to include published/archived, as well clearing up what "visibility" means
- Making the `info` command a bit nicer to read
=> PLAT-13541: Adjusting based on feedback from product

scripts/feedback.js, scripts/logout.js, scripts/modules.js, scripts/publish.js, scripts/utils/apiClient.js
PLAT-13346
Adding central handling of 401 errors
- Should continue to work as normal
- run `node index.js config set token abc123` to set an invalid token, then run any api based command like `node index.js modules list`
=> PLAT-13346: Adding central error handling for unauthenticated api client action

README.md, index.js, package.json, scripts/amplitude/constants.js, scripts/amplitude/scripts.js, scripts/amplitude/wrapper.js, scripts/create.js, scripts/feedback.js, scripts/logout.js, scripts/modules.js, scripts/publish.js, scripts/utils/apiClient.js, scripts/utils/user.js
This PR merges changes from develop into qa.
=> Merge develop into qa

.github/workflows/build-deploy.yml, .github/workflows/create-github-release.yml
CBDEVOPS-478
_Related PRs:_
_enable slack notification for prod deployment_
=> CBDEVOPS-478 enable slack notification for prod deployment

index.js
Reverts crowdbotics/modules#1105 to figure out a non-breaking option.
=> Revert "hotfix: allow server to ignore tracking"

index.js, package.json, scripts/utils/sentry.js, yarn.lock
PLAT-13781
_Related PRs:_
Tracking unhandled errors to sentry
=> PLAT-13781: Adding sentry monitoring to cli

scripts/utils/apiClient.js, scripts/utils/user.js
PLAT-14028
_Related PRs:_
- Fixing issue where unauthenticated user was failing the cli
- Need a way to bypass the common apiClient error handling
=> PLAT-14028: Fixing error where unauthenticated requests were failing cli

scripts/publish.js, scripts/utils/response.js
HOLDING OFF MERGE TIL DEVELOP IS RELEASED
Plat-13978
_Related PRs:_
- Updating handling of cli publish action based on a richer set of api responses and status codes.
**202 - enter the polling wait for success state**
**400 - print the field validation errors nicely from the BE**
**401 - print a client side "unauthorized" error**
**403 - print a client side "Current user is unauthorized to publish modules."**
**404 - try to print the "message" property returned by the BE. if it doesnt exist, print a generic "unexpected error"
any other - print generic "unexpected error" message.**
=> Plat-13978 display error

.github/workflows/build-deploy.yml
=> CBDEVOPS-503 update release tag

package.json, yarn.lock
[PI-298](https://crowdbotics.atlassian.net/browse/PI-298)
Upgrade the following packages:
- fast-xml-parser: `4.4.1`
- dset: `3.1.4`
- babel/traverse `7.25.6`
- ws: `7.5.10`
- brace: `^3.0.3`
_Related PRs:_
[PI-298]: https://crowdbotics.atlassian.net/browse/PI-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade fast-xml-parser, dset, babel, ws, and brace to incorporate latest bug fixes and improvements
