crowdbotics/modules

- scripts/add.js
- scripts/remove.js
This PR updates the `remove.js` script to support any kind of module, by comparing
each file path to the meta root property and thus obtaining relative paths that
get removed one by one.
Closes #56
> Support removing any kind of module with npm run remove

- scripts/add.js
- scripts/parse.js
- scripts/remove.js
This PR improves handling `node_modules` directories, removing them on `add`, `remove` and `parse` commands.
> Cleanup node_modules

- scaffold/template/custom/.github/dependabot.yml
Change dependabot updates for python to lockfile only. This should prevent major version changes.
This was already added to the web scaffold. [This app](https://github.com/crowdbotics-apps/dependabot2108102-d-22866/pulls) demonstrates that it works.
Generated apps should only get minor updates as specified in Pipfile.
> Restrict dependabot python updates to lockfile only

- package.json
- scripts/add.js
- scripts/parse.js
- scripts/remove.js
PLAT-XXXX
_Related PRs:_
This PR removes the Node.js version limit in the `engines` property of the `package.json` file.
It also adds `existsSync` checks for potentially missing directories.
The following test scenario should work.
```
nvm install 16.6.1 # or your node.js version manager of choice
yarn run bootstrap
yarn run add react-native-app-menu
yarn run remove react-native-app-menu
yarn run template
```
> Node.js v16.6.1 support

- dist/cookie/{{cookiecutter.project_slug}}/options/options.js
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/options/options.js
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/options/options.js
PLAT-XXXX
_Related PRs:_
This PR adds the `StyleSheet` import to the `options.js`, making it available for use in options.
Create a demo app `yarn run demo`, look for the file `options/options.js`, make sure the import is present.
> Add StyleSheet to scaffold options.js

- dist/cookie/{{cookiecutter.project_slug}}/ios/fastlane/Fastfile
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/ios/fastlane/Fastfile
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/ios/fastlane/Fastfile
PLAT-5612
_Related tickets:_ PLAT-5590, PLAT-5589
_Related PRs:_ #3139
- An update to the Fastfile configuration where it uploads the `app_privacy_details.json` to app store
- Regenerated the scaffold using `npm run bootstrap` to include the updates
- I have tested this manually through a dummy app store app using my own app store account to check if the privacy policy options are updated as described in the json
- The Appetize deployments succeeded with the changes
1. Create a react native app
2. Deploy an app
3. Change iOS Privacy Options under settings
4. Deploy again
5. The Privacy Options on the App Store App should be updated accordingly
This can probably not be tested on App Store for free apps (cause they're deployed to Appetize) so we'll need to create a dummy app that's deployed …
> PLAT-5612 Add fastlane commands for processing iOS privacy policy

- modules/terms-and-conditions/backend/modules/terms_and_conditions/README.md
- modules/terms-and-conditions/backend/modules/terms_and_conditions/viewsets.py
- modules/terms-and-conditions/modules/terms-and-conditions/README.md
- modules/terms-and-conditions/modules/terms-and-conditions/index.js
- modules/terms-and-conditions/modules/terms-and-conditions/options.js
PLAT-XXXX
N/A
- [] Minor changes
This adds support for using Module Options in the Terms and Condition module. Before, to use the module, a user would need to edit the code in `index.js` to point to an endpoint on their production server. Now they can now edit this value with module options - in the new `options.js` file. Once the UI goes live, this should make configuring this module require virtually no technical experience: A user simply adds the module via the storyboard, copy and pastes their production URL into the module options UI, and then uses the admin panel to add their Terms and Conditions.
Aside from normal review, I would test by spinning up a demo project, adding the terms and conditions module using the `npm run add` command and then setting the url in `options.js` to …
> Update Terms and Conditions for Module Options

- dist/cookie/{{cookiecutter.project_slug}}/App.js
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/App.js
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/App.js
PLAT-XXXX
_Related PRs:_
Issue:
https://sentry.io/organizations/crowdbotics-corporation/issues/2462560205/?project=1464665&query=is%3Aunresolved
Fixes recurring issue with overlap between JSX prop syntax and cookiecutter template tags, by moving the options into a variable.
Scaffold should work properly in staging. No impact here.
> Move screenOptions prop to a variable to avoid cookiecutter template tag clashes

- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/yarn.lock
- modules/django-articles/articles/models.py
PLAT-XXXX
_Related PRs:_
Fixes `django-articles` options import, which is from a local module and for that reason it needs to start with `.`.
``` sh
yarn run demo
yarn run add django-articles
cd demo/backend
pipenv install
cp .env.example .env # add sqlite
pipenv shell
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```
And check if it shows up in the Admin panel.
> Fix django-articles options import

- dist/cookie/{{cookiecutter.project_slug}}/options/options.js
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/options/options.js
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/options/options.js
PLAT-XXXX
_Related PRs:_
This PR hotfixes the `globalOptions` urls to `HelloWorld`, which will be replaced by the `cookiecutter.project_slug` template tag.
Before:
``` javascript
export const globalOptions = {
name: "{{cookiecutter.project_slug}}Identifier",
url: "https://{{cookiecutter.project_slug}}Identifier.botics.co",
api: "https://{{cookiecutter.project_slug}}Identifier.botics.co/api/v1"
}
```
After:
``` javascript
export const globalOptions = {
name: "{{cookiecutter.project_slug}}",
url: "https://{{cookiecutter.project_slug}}.botics.co",
api: "https://{{cookiecutter.project_slug}}.botics.co/api/v1"
}
```
> remove Identifier on globalOptions

- dist/cookie/{{cookiecutter.project_slug}}/.github/dependabot.yml
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/.github/dependabot.yml
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/.github/dependabot.yml
The Dependabot team has requested that we remove all day and time settings from our config. This will avoid concentrating all runs at the same time and putting undo stress on their infrastructure.
Nothing to test. Day and time config are optional. Without them dependabot will control when it runs (default is Monday).
> Remove day and time from dependabot config

- dist/cookie/{{cookiecutter.project_slug}}/ios/fastlane/Fastfile
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/ios/fastlane/Fastfile
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/ios/fastlane/Fastfile
_Related tickets:_ PLAT-5590
Fixes path to privacy details JSON file. Fastlane runs from its own directory but build commands end up running from the `ios` directory, requiring the added `fastlane/` path.
Tested in a review app here: https://github.com/crowdbotics-dev/dan5590-09281-1/blob/master/ios/fastlane/Fastfile#L59
> Add missing fastlane path to upload_app_privacy_details_to_app_store

- scaffold/template/custom/.circleci/generate_mobile_config.sh
PLAT-6341
- _xcode version changed to 13.0.0 for support in circleci_
1. _Create react native app in [crowdbotics-slack-dev](https://crowdbotics-slack-dev.herokuapp.com/)_
2. _Make sure plan for app is paid one because IOS build will be made only for paid apps_
3. _Deploy mobile app_
4. _IOS build successful message should appear in `Activity` section of `App Activity`_
> PLAT-6341: xcode version changed to 13.0.0

- dist/cookie/{{cookiecutter.project_slug}}/.circleci/generate_mobile_config.sh
- dist/raw/ProjectName/.circleci/generate_mobile_config.sh
- scaffold/template/custom/.circleci/generate_mobile_config.sh
PLAT-6341
_`generate_mobile_config.sh` file changed in cookiecutter to update xcode version to `13.0.0`_
> PLAT-6341: config file generated for cookiecutter with updated xcode version

- dist/cookie/{{cookiecutter.project_slug}}/metro.config.js
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/metro.config.js
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/metro.config.js
None
Configures metro resolver `sourceExts` property to include the `jsx` file extension.
https://facebook.github.io/metro/docs/configuration/#sourceexts
You should be able to add `.jsx` files to your module.
> Metro config - Support for jsx file extensions

- .eslintrc.json
- .github/workflows/lint.yml
- docs/authoring.md
- docs/commands.md
- package.json
- yarn.lock
PLAT-7050
This PR adds ESLint and related dependencies alongside an `.eslintrc.json` configuration. Module authors will be able to run `yarn run eslint modules/<their-module>` to lint their code, or for reviewers `yarn lint` to lint all modules.
Adds [Action ESLint](https://github.com/marketplace/actions/action-eslint) that runs ESLint on Pull Request, only on the files that were changed in said PR.
Resources:
https://eslint.org
https://github.com/standard/standard
> Add ESLint w/ standard config and React plugin

- dist/cookie/{{cookiecutter.project_slug}}/metro.config.js
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/metro.config.js
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/metro.config.js
_Related PRs:_
This PR adds support for `.ts` `.tsx` file extensions. Builds can fail when trying to resolve navigation libraries that depend on those extensions.
Run a demo app, it should build successfully.
> Add ts and tsx to metro resolver extensions

- modules/screen-login/index.js
N/A
Using the native API instead of `react-native-gesture-handler `for login screen. You can test the code on snack and you will see that they behave the same: https://snack.expo.dev/@alinetavares/touchableopacity
Resulting screen rendering and behavior should not change
> Hotfix: Favor native library over 3rd party for TouchableOpacity in screen

- scripts/demo.js
Changes the branch to checkout on [django-scaffold](https://github.com/crowdbotics/django-scaffold) when running `yarn run demo` to `master`. `develop` is a stale branch.
> Update cookiecutter --checkout to master

- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/yarn.lock
- modules/camera/backend/modules/camera/apps.py
- modules/django-articles/articles/apps.py
- modules/django-articles/articles/models.py
- modules/django-push-notifications/apps.py
- modules/django-push-notifications/meta.json
- modules/django-social-auth/apps.py
- modules/django-social-auth/meta.json
- modules/payments/backend/modules/payments/apps.py
Relates to https://github.com/crowdbotics/django-scaffold/pull/396
Changes introduced:
- Add `apps.py` on all Django modules so that our `manifest.py` loading mechanism works
- Fix `get_options` call, BE code generation uses full module name for key
- Update modules json via `yarn run bootstrap` 
- Rename all django modules to use underscore as word separator (both in module path and apps.py)
Checkout and then run:
```sh
yarn run demo
yarn run add django-articles
cd demo/backend
pipenv install --dev
cp .env.template .env # and modify it, remove DATABASE_URL line to use sqlite
pipenv shell
python manage.py migrate # should do modules.articles migrations
python manage.py show_urls # should boot up django correctly and show urls
python manage.py shell # manual testing if you want
```
> Module Options - Add apps.py to Django modules and fix `get_options`

- dist/cookie/{{cookiecutter.project_slug}}/package.json
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/package.json
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/dependencies.json
Support for RN 0.63 was dropped. Next supported version is 0.64.3, and we are on 0.64.2. https://github.com/software-mansion/react-native-reanimated/commit/342cb5b8fd810d9947c61c44f2767fcc2483b8cd#diff-49c2df30272bc7a6770fc503b2304079ad0a171dddc7b9015c354acccabdc17e
This PR locks the latest minor version before the commit.
``` sh
yarn run demo
cd demo
bundle install
cd android
bundle exec fastlane deploy_appetize
```
When following the steps above - it should build.
> Fix android build - Limit react-native-reanimated to patch

- scripts/cookie.js
- scripts/demo.js
- scripts/parse.js
- scripts/raw.js
Added exists checks for the directories that we clean up on scripts,
before actually trying to remove them.
`yarn run bootstrap` should not output errors on a fresh git clone.
> [scripts] check if dir exists before removing

- modules/payments/backend/modules/payments/payments/services/StripeService.py
- Add default value to stripe.api_key to fix operations while is not
yet configured
(Out-of-Ticket)
Once payments is installed, it requires to set the env var STRIPE_API_KEY. While it is not set, operations will fail (like uninstalling, model builder, etc.). Provide a default for the var to prevent that.
Spotted here: https://github.com/crowdbotics/crowdbotics-slack-app/pull/3641
Install and uninstall the payments module
> Update payments module

- modules/faq/modules/faq/options.js
Removes the color reference and replaces it with the string value. This enables this module options to be parsed once again (parser doesn't handle following references/bindings).
Options parsing should work for this module.
> Remove variable reference in option.js stylesheet

- dist/cookie/{{cookiecutter.project_slug}}/ios/fastlane/Fastfile
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/ios/fastlane/Fastfile
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/ios/fastlane/Fastfile
PLAT-9139
_Related tickets:_ PLAT-8731
_Related PRs:_
Add `itc_provider` to `upload_to_testflight` lane of iOS Fastfile
1. New scaffolds should have the `itc_provider` within the specified iOS Fastfile lane
2. Deploy to TestFlight and App Store should work
> PLAT-9139 Add itc_provider to iOS Fastfile

- dist/cookie/{{cookiecutter.project_slug}}/options/options.js
- dist/cookie/{{cookiecutter.project_slug}}/yarn.lock
- dist/raw/ProjectName/options/options.js
- dist/raw/ProjectName/yarn.lock
- scaffold/template/custom/options/options.js
Changed the placeholder for options `api` and `url` values so that when cookiecut' it uses the dashed slug instead of the underscore slug.
Generate an app, notice how `options.js` now uses `{{cookiecutter.project_dash_slug}}` value.
> Options - use project_dash_slug, not project_slug

- modules/react-native-app-menu/options.js
PLAT-9711
Removes the use of `StatusBar` for setting the padding top value. Options parser doesn't support this syntax yet.
N/A
> PLAT-9711 - Hotfix: App Menu options styles syntax

- config.js
- dist/cookie/{{cookiecutter.project_slug}}/.crowdbotics.json
- dist/cookie/{{cookiecutter.project_slug}}/webpack.config.js
- manifest/210-to-211.json
- scaffold/CHANGELOG.md
- scaffold/package.json
- scaffold/template/custom/.crowdbotics.json
- scaffold/template/custom/webpack.config.js
PLAT-11673
Removed `node_modules` from the list of paths that are to be transpiled via babel. Included `react-native-reanimated` which is the exception, we want to transpile that library.
Web builds should work locally.
> Fix - Fix web build issues with node_modules on ESM format

- CHANGELOG.md
- package.json
- scripts/manifest.js
Prevent updating manifest files by default (those are meant to be immutable). Changes to the scaffold are made under a version bump.
Allow for forcing updates with `--force` flag.
Running `yarn run manifest` in this branch should show the error.
> scripts - prevent manifest updates by default

- CHANGELOG.md
- index.js
- package.json
Whenever version is not 1.1.0 we can't read project_name and the other context variables from the same exact XML properties. Reading from the [.crowdbotics.json](https://github.com/crowdbotics/modules/blob/df3d8661c2f41b61c14677dd35affc88b2f23912/scaffold/template/custom/.crowdbotics.json#L5-L12) file is more reliable.
Upgrade tool should read from the file instead of parsing xml properties for apps > 1.1.0.
> Hotfix - read cookiecutter context from .crowdbotics.json

- index.js
- scripts/add.js
- scripts/remove.js
Added support for custom project name in `add module` command
Now we support following:
```
npx crowdbotics/modules add MODULE_NAME --project custom-module-dev-43901
```
PLAT-XXXX
_Related PRs:_
> added support for custom project name in add module command

- scripts/create.js
Added path after `/modules` for `react-native` modules on the `meta.json` file.
```
npx . demo
npx . create --name test --type react-native
npx . add react-native-test
ls demo/modules # should show a directory called "test"
```
> fix django/react-native meta.json and files paths

- modules/react-native-youtube-player/README.md
- modules/react-native-youtube-player/index.js
- modules/react-native-youtube-player/options.js
- modules/react-native-youtube-player/package.json
Update `react-native-youtube` package with `react-native-youtube-iframe`.
> Update react-native-youtube-player package and readme

- index.js
- scripts/commit-module.js
Introduced new `--source` argument so that one can run the commit command on any project, not just demo projects.
```
npx crowdbotics/modules#scripts/add-source-to-commit commit --source demo
```
> scripts: commit - add source argument

- index.js
PLAT-13347
_Related PRs:_
- findGitRoot should be called on demand: not all commands require git root and can b e global actions: module listing, login, etc.
- Properly showing helpful validation error 
- using this PR, run the index.js file outside of this repo (in a non-git directory). Expect to see a helpful message that directs user to our documentation on how to use modules.
- try to use a non-git command (e.g. login) and it should work normally
- use a command that needs git root inside a git repository should work fine
> PLAT-13347: Guard git-find-root to be executed on demand and validated

- .github/workflows/release-to-qa.yml
[CBDEVOPS-362](https://crowdbotics.atlassian.net/browse/CBDEVOPS-362)
_Related PRs:_
Clone github-actions repo and use release-to-qa workflow
[CBDEVOPS-362]: https://crowdbotics.atlassian.net/browse/CBDEVOPS-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update release-to-qa workflow to work with reusable github-actions

- index.js
- scripts/amplitude/constants.js
- scripts/amplitude/scripts.js
- scripts/amplitude/wrapper.js
- scripts/utils/user.js
PLAT-13612
_Related PRs:_ https://github.com/crowdbotics/vue-dash-5104/pull/4663
Did you make changes to modules or create a new module?
Updated amplitude tracking to respect the send the same properties as the Vue dashboard. The following events are being tracked:
- List Modules
- Publish Modules
- View Module Details
- Create Module
- Archive Module
- Unarchive Module
- Upgrade Scaffold
**Notes**: 
- we don't have any app-specific actions in the CLI, so app-related properties were skipped
- Although I introduced the concept of `currentUser` global object, I did not replace other `get /user/` API calls with this global object yet (I wanted to keep the changes scoped to amplitude-related code only)
Test and see if the events mentioned above are being sent to Amplitude.
> PLAT-13612: Adjust how CLI is tracked in Amplitude

- index.js
PLAT-XXXX
_Related PRs:_
The back-end always calls the CLI with a flag `--yes` to signal that it is supposed to use the default values. This was no longer needed, but I am leveraging this capability to skip diagnostics when running the CLI from our servers with automated scripts.
Any command with --yes will not send diagnostics nor ask to opt in
> hotfix: allow server to ignore tracking

- index.js
PLAT-XXXX
_Related PRs:_
Recreate https://github.com/crowdbotics/modules/pull/1105 with the correct check for npm_config_yes.
1. Set your `has-asked-opt-in` and `opt-in` config values to false
2. Execute `npx --yes help`: notice no amplitude request to opt in will trigger
3. Execute `npx help`: notice Amplitude request to opt in is now triggered
4. Try the same with a couple of other ore complex commands like `npx . parse --source ./modules`
> hotfix: properly check for correct npx --yes check

- index.js
- scripts/info.js
- scripts/utils/environment.js
Looking for feedback here, work in progress.
**Proposed method of usage:**
Command can opt into the environment checks it wants:
```javascript
const command = () => {
validateEnvironmentDependencies([EnvironmentDependency.Yarn, EnvironmentDependency.Git]);
// can continue with command
}
```
By default, all dependencies expected will be validated:
```javascript
const command = () => {
validateEnvironmentDependencies();
// can continue with command
}
```
Previous dependency validations will be cached. Command can force re-validation if necessary
```javascript
const command = () => {
validateEnvironmentDependencies([EnvironmentDependency.Yarn], true);
// can continue with command
}
```
PLAT-13620
_Related PRs:_
- …
> PLAT-13620: Adding new environment dependency validation

- scripts/analytics/config.js
PLAT-XXXX
_Related PRs:_
Amplitude events are never being sent to production because the comparison between the host value (compared to the default host) was off one character (/)
Set host to production URL
Notice SEGMENT_API_KEY being the production key, not staging
> hotfix: default host for events should always be production

- .circleci/config.yml
Update the Xcode version from 14.1.0 to 14.2.0 to ensure compatibility with the latest iOS features and improvements. Change the resource class from macos.x86.medium.gen2 to macos.m1.medium.gen1 to leverage the performance benefits of Apple's M1 architecture, which can lead to faster build times and more efficient resource usage.
PLAT-XXXX
_Related PRs:_
> ci(config.yml): update Xcode version and resource class for iOS job

- .circleci/config.yml
Remove the _JAVA_OPTIONS environment variable as it is no longer needed. The options it provided are now default in newer Java versions, making this configuration redundant. This change simplifies the CircleCI configuration and reduces potential confusion or conflicts with Java settings.
PLAT-XXXX
_Related PRs:_
> chore(ci): remove deprecated _JAVA_OPTIONS from CircleCI config
